# Snowflake MCP Server Service Configuration
# This file defines which Cortex services and tools are enabled
# Authentication credentials are passed via CLI arguments

# Connection Settings
connection:
  database: ANALYTICS_DW
  schema: PROD_SALES_DM
  warehouse: TABLEAU_WH
  role: DEVELOPER

# Cortex Agent Services
agent_services: []
  # Example:
  # - service_name: my_agent
  #   description: Agent that helps with sales data
  #   database_name: ANALYTICS_DW
  #   schema_name: PROD_SALES_DM

# Cortex Search Services
search_services: []
  # Example:
  # - service_name: my_search
  #   description: Search service for customer documents
  #   database_name: ANALYTICS_DW
  #   schema_name: PROD_SALES_DM

# Cortex Analyst Services
analyst_services: []
  # Example:
  # - service_name: sales_analyst
  #   semantic_model: ANALYTICS_DW.PROD_SALES_DM.SALES_SEMANTIC_VIEW
  #   description: Analyst for sales metrics and trends

# Enable/Disable Tool Groups
other_services:
  object_manager: true    # Database, schema, table, view management
  query_manager: true     # SQL execution capabilities
  semantic_manager: true  # Semantic view discovery and querying

# SQL Statement Permissions
sql_statement_permissions:
  - Alter: false
  - Command: true
  - Comment: false
  - Commit: false
  - Create: false
  - Delete: false
  - Describe: true
  - Drop: false
  - Insert: false
  - Merge: false
  - Rollback: false
  - Select: true
  - Transaction: false
  - TruncateTable: false
  - Unknown: false  # Block unknown SQL statement types
  - Update: false
  - Use: true
