# Snowflake MCP Server Configuration (Minimal)
# Credentials are passed via CLI arguments
# This file only configures service features

# Cortex services (empty for now - can add later)
agent_services: []
search_services: []
analyst_services: []

# Enable core service groups
other_services:
  object_manager: True
  query_manager: True
  semantic_manager: False

# SQL permissions (read-only for safety)
sql_statement_permissions:
  - Select: True
  - Show: True
  - Describe: True
  - Use: True
  - Create: False
  - Update: False
  - Delete: False
  - Drop: False
  - Insert: False
  - Truncate: False
  - Alter: False
  - Command: False
