name: Claude Completion Verification

on:
  pull_request:
    types: [labeled]

jobs:
  verify-completion:
    name: Verify Manual Completion
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'claude:complete')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Merge latest main for verification
        run: |
          echo "🔄 Merging latest main to get complete project structure..."
          git config --local user.email "action@github.com"
          git config --local user.name "Claude Completion Verification"
          git fetch origin main
          git merge origin/main --no-edit || echo "Merge conflict - will proceed with available files"

      - name: Verify manual completion was performed
        run: |
          echo "🔍 Verifying that /complete command was executed manually..."

          # Extract project name from branch name
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "Branch name: $BRANCH_NAME"

          # Check if this looks like a project branch
          if [[ "$BRANCH_NAME" =~ ^(feature|fix|research)- ]]; then
            PROJECT_NAME="$BRANCH_NAME"
            echo "Project name detected: $PROJECT_NAME"
          else
            echo "⚠️ Branch doesn't follow project naming convention, checking for any active projects..."
            PROJECT_NAME=""
          fi

          # Check if project was moved from active to completed
          COMPLETION_VERIFIED=false

          if [ -n "$PROJECT_NAME" ]; then
            # Check specific project archive
            CURRENT_MONTH=$(date +%Y-%m)
            ARCHIVE_PATH="projects/completed/$CURRENT_MONTH/$PROJECT_NAME"

            if [ -d "$ARCHIVE_PATH" ]; then
              echo "✅ Found archived project: $ARCHIVE_PATH"
              COMPLETION_VERIFIED=true
            else
              # Check if project still exists in active (not completed)
              ACTIVE_PATH="projects/active/$PROJECT_NAME"
              if [ -d "$ACTIVE_PATH" ]; then
                echo "❌ Project still exists in active directory: $ACTIVE_PATH"
                echo "Please run '/complete $PROJECT_NAME' to properly archive the project"
              else
                echo "⚠️ Project not found in active or completed directories"
                echo "Checking for any completed projects this month..."
                if [ -d "projects/completed/$CURRENT_MONTH" ] && [ "$(ls -A projects/completed/$CURRENT_MONTH 2>/dev/null)" ]; then
                  echo "Found completed projects this month:"
                  ls -la "projects/completed/$CURRENT_MONTH/"
                  COMPLETION_VERIFIED=true
                else
                  echo "No completed projects found for $CURRENT_MONTH"
                fi
              fi
            fi
          else
            # No specific project detected, check if any completion happened recently
            CURRENT_MONTH=$(date +%Y-%m)
            if [ -d "projects/completed/$CURRENT_MONTH" ] && [ "$(ls -A projects/completed/$CURRENT_MONTH 2>/dev/null)" ]; then
              echo "✅ Found completed projects this month (no specific project detected):"
              ls -la "projects/completed/$CURRENT_MONTH/"
              COMPLETION_VERIFIED=true
            else
              echo "❌ No completed projects found for $CURRENT_MONTH"
            fi
          fi

          if [ "$COMPLETION_VERIFIED" = false ]; then
            echo ""
            echo "❌ Manual completion verification failed!"
            echo ""
            echo "Required: Project must be properly completed using '/complete' command"
            echo "This ensures:"
            echo "  • Knowledge extraction and preservation"
            echo "  • Proper project archival"
            echo "  • Agent capability updates"
            echo "  • Documentation enhancements"
            echo ""
            echo "To resolve:"
            if [ -n "$PROJECT_NAME" ]; then
              echo "  1. Run: /complete $PROJECT_NAME"
            else
              echo "  1. Run: /complete [your-project-name]"
            fi
            echo "  2. Verify project moved to projects/completed/[YYYY-MM]/"
            echo "  3. Re-add the claude:complete label"
            exit 1
          fi

          echo ""
          echo "✅ Manual completion verification successful!"
          echo "Project has been properly completed and archived."

      - name: Report verification status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const conclusion = '${{ job.status }}';
            const prNumber = context.issue.number;

            let message = '';
            if (conclusion === 'success') {
              message = `## ✅ Manual Completion Verified

PR #${prNumber} has been verified as properly completed using the \`/complete\` command.

**Verification confirmed:**
- ✅ Project properly archived to \`projects/completed/[YYYY-MM]/\`
- ✅ Knowledge extraction and preservation completed
- ✅ Agent capability updates applied
- ✅ Documentation enhancements preserved

**What this means:**
- The developer manually ran \`/complete [project-name]\`
- All ADLC completion benefits have been applied
- Project is ready for final review and merge

The PR is now ready for final review and merge.`;
            } else {
              message = `## ❌ Manual Completion Required

PR #${prNumber} requires manual completion before merge.

**Missing:** Project has not been properly completed using the \`/complete\` command.

**To resolve:**
1. Run: \`/complete [project-name]\` in Claude Code
2. Verify the project moved to \`projects/completed/[YYYY-MM]/\`
3. Re-add the \`claude:complete\` label to re-trigger verification

**Benefits of manual completion:**
- Knowledge extraction and preservation
- Agent capability updates
- Documentation enhancements
- Proper project archival

Please check the [action logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.`;
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });

      - name: Clean up completion label
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            // Remove the claude:complete label only on successful verification
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'claude:complete'
              });
              console.log('✅ Removed claude:complete label after successful verification');
            } catch (error) {
              console.log('Label already removed or not found');
            }