name: dbt Issue Sleuthing

on:
  repository_dispatch:
    types: [dbt-issue-sleuth]
  workflow_dispatch:
    inputs:
      repository:
        description: 'Target repository (e.g., graniterock/dbt_cloud)'
        required: true
        type: string
      project:
        description: 'dbt project name (dbt_cloud or roy_kent)'
        required: true
        type: string

jobs:
  sleuth-dbt-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da-agent-hub
      uses: actions/checkout@v4

    - name: Extract dispatch payload
      id: payload
      run: |
        if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          echo "repository=${{ github.event.client_payload.repository }}" >> $GITHUB_OUTPUT
          echo "project=${{ github.event.client_payload.project }}" >> $GITHUB_OUTPUT
          echo "trigger=${{ github.event.client_payload.trigger }}" >> $GITHUB_OUTPUT
          echo "run_id=${{ github.event.client_payload.run_id }}" >> $GITHUB_OUTPUT
        else
          echo "repository=${{ github.event.inputs.repository }}" >> $GITHUB_OUTPUT
          echo "project=${{ github.event.inputs.project }}" >> $GITHUB_OUTPUT
          echo "trigger=manual" >> $GITHUB_OUTPUT
          echo "run_id=${{ github.run_id }}" >> $GITHUB_OUTPUT
        fi

    - name: Investigate with Claude
      uses: anthropics/claude-code-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        claude_code_oauth_token: ${{ secrets.ANTHROPIC_API_KEY }}
        claude_args: |
          --model claude-3-5-sonnet-20241022
        prompt: |
          # dbt Issue Investigation

          Please investigate recent dbt issues in **${{ steps.payload.outputs.repository }}** for the **${{ steps.payload.outputs.project }}** project.

          ## Context
          - **Repository**: ${{ steps.payload.outputs.repository }}
          - **Project**: ${{ steps.payload.outputs.project }}
          - **Trigger**: ${{ steps.payload.outputs.trigger }}
          - **Run ID**: ${{ steps.payload.outputs.run_id }}

          ## Investigation Tasks

          1. **Find Recent Issues**: Search for open issues with Claude metadata in the target repository
          2. **Prioritize by Metadata**: Focus on high-priority issues and critical error types
          3. **Multi-Agent Analysis**: Use appropriate agents based on affected systems:
             - `dbt-expert`: For model compilation and test failures
             - `snowflake-expert`: For warehouse-level performance issues
             - `tableau-expert`: For report model issues (rpt_* models)
             - `business-context`: For business logic validation
             - `da-architect`: For cross-system analysis

          4. **Investigation Steps**: For each high-priority issue:
             - Analyze the error details and patterns
             - Check related models and dependencies
             - Examine recent changes that might have caused the issue
             - Look for similar patterns across other models
             - Provide specific fix recommendations

          5. **Update Issues**: Add investigation findings as comments with:
             - Root cause analysis
             - Recommended fixes
             - Related issues or patterns
             - Priority assessment for team action

          ## Focus Areas
          - Schema compilation errors (highest priority)
          - Data quality issues indicating upstream problems
          - Business logic validation failures
          - Cross-system integration issues

          Please proceed with the investigation and provide a summary of findings.

          ## Available Actions for Users

          After investigation, users can interact with me by:
          - **@claude create PR** - I'll create a pull request with the fix
          - **@claude investigate [specific aspect]** - I'll do deeper analysis
          - **Assign to claude[bot]** - I'll automatically attempt to fix the issue
          - **Add label `claude:fix`** - I'll create a PR to fix the issue
          - **Add label `claude:investigate`** - I'll do additional investigation

          I'm here to help collaboratively resolve dbt issues!
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DBT_CLOUD_API_TOKEN: ${{ secrets.DBT_CLOUD_API_TOKEN }}
        DBT_CLOUD_ACCOUNT_ID: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}

    - name: Create Investigation Summary
      if: always()
      run: |
        echo "📋 Investigation completed for ${{ steps.payload.outputs.repository }}"
        echo "Repository: ${{ steps.payload.outputs.repository }}"
        echo "Project: ${{ steps.payload.outputs.project }}"
        echo "Trigger: ${{ steps.payload.outputs.trigger }}"
        echo "Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"